version: "3.8"
services:
  database:
    image: postgres:15.2-alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=edelweiss
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
      - ./sql/users.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  database:
    driver: local