version: "3.8"
services:
  database:
    image: postgres:15.2-alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=edelweiss
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
      - ./sql/tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  test_database:
    image: postgres:15.2-alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=edelweiss_test
    ports:
      - '5433:5432'
    volumes:
      - ./sql/tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  database:
    driver: local
  test_database:
    driver: local