spring:
  application:
    name: edelweiss-api-gateway
  cloud:
    gateway:
      routes:
        - id: doctor-api
          uri: http://localhost:8081
          predicates:
            Path=/physician/**
        - id: pharmacy-api
          uri: http://localhost:8082
          predicates:
            Path=/pharmacy/**
        - id: patient-api
          uri: http://localhost:8083
        - id: prescription-api
          uri: http://localhost:8084
        - id: appointment-api
          uri: ttp://localhost:8085
          predicates:
            Path=/physician/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/