spring:
  application:
    name: edelweiss-doctor-api
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/edelweiss
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
  error:
    include-message: always

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/