logging:
  level:
    org:
      springframework:
        security: TRACE

spring:
  application:
    name: edelweiss-doctor-api
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/edelweiss
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
  error:
    include-message: always